---
- name: update web servers
  hosts: all
  become: yes
  tasks:
    - name: update webserver
      apt:
        name: apache2
        update_cache: yes
        state: latest

- name: update db servers
  hosts: dbserver
  become: yes
  tasks:
    - name: postgresql installation
      apt: 
        name: postgresql
        state: present

    - name: enabling postgress
      service: 
        name: postgresql
        state: started