---
- name: update web servers
  remote_user: yes
  hosts: all
  tasks:
    - name: update webserver
      apt:
        name: apache2
        state: latest
        update_cache: yes

- name: update db servers
  remote_user: yes
  hosts: dbserver
  tasks:
    - name: postgresql installation
      apt: 
        name: postgresql
        state: present

    - name: enabling postgress
      service: 
        name: postgresql
        state: started