---
- name: update web servers
  hosts: all
  become: yes
  tasks:
    - name: Retry a task until a certain condition is met
      shell: echo one
      register: result
    - debug:
        msg: {{result.stdout}}