---
- name: subelements demo
  hosts: all
  become: yes
  vars:
    users:
      - name: alice
        authorized:
          - /tmp/alice/onekey.pub
          - /tmp/alice/twokey.pub
        groups:
          - wheel
          - docker
      - name: bob
        authorized:
          - /tmp/bob/id_rsa.pub
        groups:
        - docker

  tasks:
    - name: Set authorized ssh key, extracting just that data from 'users'
      authorized_key:
        user: "{{ item.0.name }}"
        key: "{{ lookup('file', item.1) }}"
      with_subelements:
         - "{{ users }}"
         - authorized
    