---
- name: subelements demo
  hosts: all
  become: yes
  users:
    - name: alice
      authorized:
        - /tmp/alice/onekey.pub
        - /tmp/alice/twokey.pub
      groups:
        - wheel
        - docker
    - name: bob
      authorized:
        - /tmp/bob/id_rsa.pub
      groups:
        - docker

  tasks:
    - name: users modification
      debug:
        msg: "{{ users | subelements('groups', skip_missing=True) }}"
