---
- name: subelements demo
  hosts: all
  become: yes
  vars:
    users:
      - name: alice
        authorized:
          - /tmp/alice/onekey.pub
          - /tmp/alice/twokey.pub
        groups:
          - wheel
          - docker
      - name: bob
        authorized:
          - /tmp/bob/id_rsa.pub
        groups:
        - docker

  tasks:
    - name: Set a variable
      set_fact:
        myvar: "{{ {{ users | subelements('groups') }} }}"
    