---
- name: subelements demo
  hosts: all
  become: yes
  vars:
    users:
      - name: alice
        authorized:
          - /tmp/foo
          - /tmp/baz
        groups:
          - wheel
          - docker
      - name: bob
        authorized:
          - /tmp/bar
        groups:
        - docker

  tasks:
    - name: Set authorized ssh key, extracting just that data from 'users'
      authorized_key:
        user: "{{ item.0.name }}"
        key: "{{ lookup('file', item.1) }}"
      with_subelements:
         - "{{ users }}"
         - authorized
    