---
- name: from and to json demo
  hosts: all
  become: yes
  tasks:
  - name: Register JSON output as a variable
    ansible.builtin.shell: cat ./ternary.yaml
    register: result

  - name: Set a variable
    ansible.builtin.set_fact:
      myvar: "{{ result.stdout | from_yaml }}"
