---
- name: from and to json demo
  hosts: all
  become: yes
  tasks:
  - name: Register JSON output as a variable
    shell: cat ternary.yaml
    register: result

  - name: see what register has
    debug:
      msg: "{{register}}"

  - name: Set a variable
    set_fact:
      myvar: "{{ result.stdout | from_yaml }}"
