---
- name: ternary test
  hosts: all
  become: yes
  tasks:
    - name: Ternary test
      debug:
        msg: "variable status is {{ (status == 'needs_restart') | ternary('restart', 'continue') }}"
