---
- name: ternary test
  hosts: all
  become: yes
  vars:
    - enabled=true
  tasks:
    - name: Ternary test
      debug:
        msg: "variable status is {{ enabled | ternary('restart', 'continue') }}"
